version: "3.7"

services:
  elasticsearch:
    container_name: course_elastic
    build:
      context: .
      dockerfile: ./Dockerfiles/Dockerfile_elastic
    command: tail -F anything
    network_mode: host
    volumes:
      - ./scripts/elastic:/scripts
      - ./inputs:/inputs
    cpu_count: 1 
    cpus: 1
    mem_limit: 1g

  kibana:
    container_name: course_kibana
    build:
      context: .
      dockerfile: ./Dockerfiles/Dockerfile_kibana
    command: tail -F anything
    network_mode: host
    cpu_count: 1 
    cpus: 1
    mem_limit: 2g

  neo4j:
    container_name: course_neo4j
    build:
      context: .
      dockerfile: ./Dockerfiles/Dockerfile_neo4j
    command: tail -F anything
    network_mode: host
    volumes:
      - ./scripts/neo4j:/scripts
    cpu_count: 1 
    cpus: 1
    mem_limit: 1g
