version: "3.7"

services:
  elasticsearch:
    container_name: course_elastic
    build:
      context: ./for_install/elastic
      dockerfile: ./Dockerfile_elastic
    command: tail -F anything
    network_mode: host
    volumes:
      - ./scripts/elastic:/scripts
      - ./inputs:/inputs
    cpu_count: 1 
    cpus: 1
    mem_limit: 1g

  kibana:
    container_name: course_kibana
    build:
      context: ./for_install/kibana
      dockerfile: ./Dockerfile_kibana
    command: tail -F anything
    network_mode: host
    cpu_count: 1 
    cpus: 1
    mem_limit: 2g

  neo4j:
    container_name: course_neo4j
    build:
      context: ./for_install/neo4j
      dockerfile: ./Dockerfile_neo4j
    command: tail -F anything
    network_mode: host
    volumes:
      - ./scripts/neo4j:/scripts
    cpu_count: 1 
    cpus: 1
    mem_limit: 1g

  spark:
    container_name: course_spark
    build:
      context: ./for_install/spark
      dockerfile: ./Dockerfile_spark
    command: tail -F anything
    network_mode: host
    volumes:
      - ./scripts/spark:/scripts
    cpu_count: 1 
    cpus: 1
    mem_limit: 2g

  pgvector:
    container_name: course_pgvector
    build:
      context: ./for_install/pgvector
      dockerfile: ./Dockerfile_pgvector
    command: tail -F anything
    network_mode: host
    volumes:
      - ./scripts/pgvector:/scripts
    cpu_count: 1 
    cpus: 1
    mem_limit: 1g