FROM ubuntu:latest

RUN mkdir /scripts

WORKDIR /scripts

RUN apt-get update 
RUN apt-get install -y ca-certificates wget lsb-release
RUN install -d /usr/share/postgresql-common/pgdg
RUN wget -O /usr/share/postgresql-common/pgdg/apt.postgresql.org.asc https://www.postgresql.org/media/keys/ACCC4CF8.asc
RUN sh -c 'echo "deb [signed-by=/usr/share/postgresql-common/pgdg/apt.postgresql.org.asc] https://apt.postgresql.org/pub/repos/apt $(lsb_release -cs)-pgdg main" > /etc/apt/sources.list.d/pgdg.list'

RUN apt-get update
RUN apt-get install -y postgresql-16
RUN apt-get install -y postgresql-contrib-16
RUN apt-get install -y python3-psycopg2

RUN apt-get install -y git gcc postgresql-server-dev-16 make
RUN git clone https://github.com/pgvector/pgvector 
RUN cd pgvector && make install